/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.jishnuc.protobuffer;

import com.github.jishnuc.proto.*;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println(new App().getGreeting());
        
        Simple.SimpleMessage.Builder builder=Simple.SimpleMessage.newBuilder();

        builder.setId(47)
                .setIsSimple(true)
                .setName("My Simple Message Name");

        builder.addSimpleList(1)
                .addSimpleList(2)
                .addSimpleList(3);

        builder.addAllSimpleList(Arrays.asList(4,5,6));

        //builder.clearSimpleList();

        System.out.println(builder.toString());

        Simple.SimpleMessage message=builder.build();
        //write proto buffer to binary file
        try(FileOutputStream outputStream=new FileOutputStream("simplemessage.bin")){
            message.writeTo(outputStream);
        }
        //send as byte array

        byte[] bytes = message.toByteArray();

        //read binary proto file to object

        try(FileInputStream inputStream=new FileInputStream("simplemessage.bin")){
            Simple.SimpleMessage messageFromFile= Simple.SimpleMessage.parseFrom(inputStream);
            System.out.println(messageFromFile);
        }

    }
}
